pairinteraction: PerturbativeInteraction Class Reference
PerturbativeInteraction Class Reference
#include <PerturbativeInteraction.h>
Public Member Functions
PerturbativeInteraction (MatrixElementCache &cache)
PerturbativeInteraction (double angle, MatrixElementCache &cache)
PerturbativeInteraction (double angle, double weak_bfield_along_z, MatrixElementCache &cache)
double getC6 (StateTwo state, double deltaN)
eigen_dense_double_t getC6 (std::vector< StateTwo > states, double deltaN)
eigen_dense_double_t getC3 (std::vector< StateTwo > states)
eigen_dense_double_t getEnergies (std::vector< StateTwo > states)
Detailed Description
Definition at line 27 of file PerturbativeInteraction.h.
Constructor & Destructor Documentation
PerturbativeInteraction() [1/3]
PerturbativeInteraction::PerturbativeInteraction (MatrixElementCache & cache)
Definition at line 21 of file PerturbativeInteraction.cpp.
PerturbativeInteraction() [2/3]
PerturbativeInteraction::PerturbativeInteraction (double angle, MatrixElementCache & cache)
Definition at line 26 of file PerturbativeInteraction.cpp.
PerturbativeInteraction() [3/3]
PerturbativeInteraction::PerturbativeInteraction (double angle, double weak_bfield_along_z, MatrixElementCache & cache)
Definition at line 31 of file PerturbativeInteraction.cpp.
Member Function Documentation
getC3()
eigen_dense_double_t PerturbativeInteraction::getC3 (std::vector< StateTwo > states)
Definition at line 300 of file PerturbativeInteraction.cpp.
References coulombs_constant, and MatrixElementCache::getElectricDipole().
getC6() [1/2]
double PerturbativeInteraction::getC6 (StateTwo state, double deltaN)
Definition at line 37 of file PerturbativeInteraction.cpp.
References coulombs_constant, StateTwo::first(), MatrixElementCache::getElectricDipole(), StateTwo::getEnergy(), MatrixElementCache::getMagneticDipole(), StateTwo::j, StateTwo::l, StateTwo::m, StateTwo::n, StateTwo::s, StateTwo::second(), and StateTwo::species.
getC6() [2/2]
eigen_dense_double_t PerturbativeInteraction::getC6 (std::vector< StateTwo > states, double deltaN)
Definition at line 126 of file PerturbativeInteraction.cpp.
References coulombs_constant, StateTwo::first(), MatrixElementCache::getElectricDipole(), StateTwo::getEnergy(), MatrixElementCache::getMagneticDipole(), and StateTwo::second().
getEnergies()
eigen_dense_double_t PerturbativeInteraction::getEnergies (std::vector< StateTwo > states)
Definition at line 329 of file PerturbativeInteraction.cpp.
References MatrixElementCache::getMagneticDipole().
The documentation for this class was generated from the following files:
/travis/libpairinteraction/PerturbativeInteraction.h
/travis/libpairinteraction/PerturbativeInteraction.cpp